export interface ROPItem {
  id: number;
  name: string;
  categoryId: number;
  size_dimensions: string;
  thread_type: string;
  material_grade: string;
  current_quantity: number;
  reorder_point_ROP: number;
  retail_price: number;
  wholesale_price?: number;
  binId?: number;
  createdAt: Date;
  updatedAt: Date;
}

export const mockROPData: ROPItem[] = [
  {
    id: 1,
    name: "Hex Bolt 1/2 x 2",
    categoryId: 1,
    size_dimensions: "1/2 inch x 2 inches",
    thread_type: "UNC",
    material_grade: "Stainless Steel 304",
    current_quantity: 5,
    reorder_point_ROP: 10,
    retail_price: 2.50,
    wholesale_price: 1.80,
    binId: 1,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-08-20"),
  },
  {
    id: 2,
    name: "Hex Nut 1/2",
    categoryId: 1,
    size_dimensions: "1/2 inch",
    thread_type: "UNC",
    material_grade: "Stainless Steel 304",
    current_quantity: 150,
    reorder_point_ROP: 20,
    retail_price: 0.75,
    wholesale_price: 0.50,
    binId: 2,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-08-18"),
  },
  {
    id: 3,
    name: "Machine Screw M8 x 20mm",
    categoryId: 2,
    size_dimensions: "M8 x 20mm",
    thread_type: "Metric",
    material_grade: "Steel Zinc Plated",
    current_quantity: 8,
    reorder_point_ROP: 15,
    retail_price: 1.20,
    wholesale_price: 0.85,
    binId: 3,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-08-22"),
  },
  {
    id: 4,
    name: "Flat Washer M8",
    categoryId: 2,
    size_dimensions: "M8",
    thread_type: "Metric",
    material_grade: "Steel Zinc Plated",
    current_quantity: 200,
    reorder_point_ROP: 30,
    retail_price: 0.15,
    wholesale_price: 0.10,
    binId: 4,
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-08-15"),
  },
  {
    id: 5,
    name: "Carriage Bolt 3/8 x 1.5",
    categoryId: 3,
    size_dimensions: "3/8 inch x 1.5 inches",
    thread_type: "UNC",
    material_grade: "Steel Zinc Plated",
    current_quantity: 3,
    reorder_point_ROP: 8,
    retail_price: 1.85,
    wholesale_price: 1.30,
    binId: 5,
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-08-23"),
  },
  {
    id: 6,
    name: "Lock Washer 3/8",
    categoryId: 3,
    size_dimensions: "3/8 inch",
    thread_type: "UNC",
    material_grade: "Steel Zinc Plated",
    current_quantity: 75,
    reorder_point_ROP: 25,
    retail_price: 0.25,
    wholesale_price: 0.18,
    binId: 6,
    createdAt: new Date("2024-04-25"),
    updatedAt: new Date("2024-08-19"),
  },
  {
    id: 7,
    name: "Socket Head Cap Screw M6 x 30mm",
    categoryId: 4,
    size_dimensions: "M6 x 30mm",
    thread_type: "Metric",
    material_grade: "Alloy Steel Black Oxide",
    current_quantity: 12,
    reorder_point_ROP: 20,
    retail_price: 2.10,
    wholesale_price: 1.50,
    binId: 7,
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-08-21"),
  },
  {
    id: 8,
    name: "Wood Screw #8 x 1.25",
    categoryId: 5,
    size_dimensions: "#8 x 1.25 inches",
    thread_type: "Wood",
    material_grade: "Steel Zinc Plated",
    current_quantity: 300,
    reorder_point_ROP: 50,
    retail_price: 0.35,
    wholesale_price: 0.25,
    binId: 8,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-08-17"),
  },
  {
    id: 9,
    name: "Eye Bolt 1/2 x 4",
    categoryId: 6,
    size_dimensions: "1/2 inch x 4 inches",
    thread_type: "UNC",
    material_grade: "Forged Steel",
    current_quantity: 4,
    reorder_point_ROP: 5,
    retail_price: 4.50,
    wholesale_price: 3.25,
    binId: 9,
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2024-08-24"),
  },
  {
    id: 10,
    name: "Threaded Rod M10 x 1m",
    categoryId: 7,
    size_dimensions: "M10 x 1 meter",
    thread_type: "Metric",
    material_grade: "Steel Zinc Plated",
    current_quantity: 25,
    reorder_point_ROP: 10,
    retail_price: 8.00,
    wholesale_price: 5.75,
    binId: 10,
    createdAt: new Date("2024-07-01"),
    updatedAt: new Date("2024-08-16"),
  },
  {
    id: 11,
    name: "Square Nut 5/8",
    categoryId: 8,
    size_dimensions: "5/8 inch",
    thread_type: "UNC",
    material_grade: "Steel Plain",
    current_quantity: 6,
    reorder_point_ROP: 12,
    retail_price: 0.90,
    wholesale_price: 0.65,
    binId: 11,
    createdAt: new Date("2024-07-20"),
    updatedAt: new Date("2024-08-22"),
  },
  {
    id: 12,
    name: "T-Nut M6",
    categoryId: 9,
    size_dimensions: "M6",
    thread_type: "Metric",
    material_grade: "Steel Zinc Plated",
    current_quantity: 45,
    reorder_point_ROP: 15,
    retail_price: 0.45,
    wholesale_price: 0.32,
    binId: 12,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-20"),
  },
];
