export enum AssignedRole {
  MANAGER = "MANAGER",
  SECRETARY = "SECRETARY",
  CASHIER = "CASHIER",
  SALES_CLERK = "SALES_CLERK",
  STOCK_MANAGEMENT = "STOCK_MANAGEMENT",
}

export interface Staff {
  id: number;
  username: string;
  password_hash: string;
  first_name: string;
  last_name: string;
  assigned_role: AssignedRole;
  is_active: boolean;
  cross_functional_roles: AssignedRole[];
}

export const mockStaffData: Staff[] = [
  {
    id: 1,
    username: "jmanager",
    password_hash: "hashed_password_1",
    first_name: "John",
    last_name: "Manager",
    assigned_role: AssignedRole.MANAGER,
    is_active: true,
    cross_functional_roles: [AssignedRole.SALES_CLERK, AssignedRole.CASHIER],
  },
  {
    id: 2,
    username: "ssecretary",
    password_hash: "hashed_password_2",
    first_name: "Sarah",
    last_name: "Secretary",
    assigned_role: AssignedRole.SECRETARY,
    is_active: true,
    cross_functional_roles: [AssignedRole.CASHIER],
  },
  {
    id: 3,
    username: "mcashier",
    password_hash: "hashed_password_3",
    first_name: "Mike",
    last_name: "Cashier",
    assigned_role: AssignedRole.CASHIER,
    is_active: true,
    cross_functional_roles: [AssignedRole.SALES_CLERK],
  },
  {
    id: 4,
    username: "asales",
    password_hash: "hashed_password_4",
    first_name: "Anna",
    last_name: "Sales",
    assigned_role: AssignedRole.SALES_CLERK,
    is_active: true,
    cross_functional_roles: [AssignedRole.CASHIER, AssignedRole.STOCK_MANAGEMENT],
  },
  {
    id: 5,
    username: "bstock",
    password_hash: "hashed_password_5",
    first_name: "Bob",
    last_name: "Stock",
    assigned_role: AssignedRole.STOCK_MANAGEMENT,
    is_active: true,
    cross_functional_roles: [AssignedRole.SALES_CLERK],
  },
  {
    id: 6,
    username: "emanager2",
    password_hash: "hashed_password_6",
    first_name: "Emily",
    last_name: "Assistant",
    assigned_role: AssignedRole.MANAGER,
    is_active: false,
    cross_functional_roles: [AssignedRole.SECRETARY],
  },
  {
    id: 7,
    username: "dcashier2",
    password_hash: "hashed_password_7",
    first_name: "David",
    last_name: "Cashier2",
    assigned_role: AssignedRole.CASHIER,
    is_active: true,
    cross_functional_roles: [],
  },
  {
    id: 8,
    username: "lsales2",
    password_hash: "hashed_password_8",
    first_name: "Lisa",
    last_name: "Sales2",
    assigned_role: AssignedRole.SALES_CLERK,
    is_active: true,
    cross_functional_roles: [AssignedRole.CASHIER],
  },
  {
    id: 9,
    username: "kstock2",
    password_hash: "hashed_password_9",
    first_name: "Kevin",
    last_name: "Stock2",
    assigned_role: AssignedRole.STOCK_MANAGEMENT,
    is_active: false,
    cross_functional_roles: [AssignedRole.SALES_CLERK, AssignedRole.CASHIER],
  },
  {
    id: 10,
    username: "rsecretary2",
    password_hash: "hashed_password_10",
    first_name: "Rachel",
    last_name: "Secretary2",
    assigned_role: AssignedRole.SECRETARY,
    is_active: true,
    cross_functional_roles: [AssignedRole.CASHIER, AssignedRole.SALES_CLERK],
  },
  {
    id: 11,
    username: "tmanager3",
    password_hash: "hashed_password_11",
    first_name: "Tom",
    last_name: "Manager3",
    assigned_role: AssignedRole.MANAGER,
    is_active: true,
    cross_functional_roles: [AssignedRole.STOCK_MANAGEMENT],
  },
  {
    id: 12,
    username: "jcashier3",
    password_hash: "hashed_password_12",
    first_name: "Jessica",
    last_name: "Cashier3",
    assigned_role: AssignedRole.CASHIER,
    is_active: true,
    cross_functional_roles: [],
  },
  {
    id: 13,
    username: "csales3",
    password_hash: "hashed_password_13",
    first_name: "Chris",
    last_name: "Sales3",
    assigned_role: AssignedRole.SALES_CLERK,
    is_active: false,
    cross_functional_roles: [AssignedRole.STOCK_MANAGEMENT],
  },
  {
    id: 14,
    username: "astock3",
    password_hash: "hashed_password_14",
    first_name: "Amanda",
    last_name: "Stock3",
    assigned_role: AssignedRole.STOCK_MANAGEMENT,
    is_active: true,
    cross_functional_roles: [AssignedRole.SALES_CLERK],
  },
  {
    id: 15,
    username: "msecretary3",
    password_hash: "hashed_password_15",
    first_name: "Mark",
    last_name: "Secretary3",
    assigned_role: AssignedRole.SECRETARY,
    is_active: true,
    cross_functional_roles: [AssignedRole.CASHIER],
  },
];
